#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
 platform :ios, '9.0'

target 'GameCommuniteDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  #network
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Moya'
  
  #网易云信sdk
  pod 'NIMSDK_LITE'
  
  #友盟社会化分享
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCCommonLog' #测试用log
  
  #苹果内购
  pod 'SwiftyStoreKit'
  
  pod 'UMCShare/Social/ReducedWeChat' # 集成微信(精简版0.2M)
  pod 'UMCShare/Social/ReducedQQ'     # 集成QQ/QZone/TIM(精简版0.5M)
  pod 'UMCShare/Social/ReducedSina'   # 集成新浪微博(精简版1M)

  
  #model
  pod 'ObjectMapper' #配合https://github.com/Ahmed-Ali/JSONExport 快速建立model
  pod 'SwiftyJSON'
  
  #UI
  pod 'MJRefresh'
  pod 'SnapKit'
  pod 'TYCyclePagerView'
  pod 'TYPagerController'
  pod 'SDCycleScrollView'
  pod 'ESTabBarController-swift' #带点击动画的tabbar
  pod 'LZImageBrowser' #图片浏览器
  pod 'Charts'
  pod 'JXSegmentedView', '~> 0.0.19' #分页控制器
  pod 'JXPagingView/Paging', '~> 1.1.15'#分页控制器
  pod 'PlaceholderTextView'
  pod 'HXPhotoPicker' #图片浏览器
  pod 'GrowingTextView', '0.7.0'
  pod 'YYText'
  pod 'DYFoldLabel'
  
  #Toast
  pod 'Toast-Swift' #弹出信息
  pod 'MBProgressHUD' #弹出信息
  
  #rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'

  #other
  pod 'Reusable'
  pod 'Then'
  pod 'KeychainAccess' #keychain
  pod 'IQKeyboardManagerSwift'
  pod 'Bugly'

end
