#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
 platform :ios, '9.0'

target 'GameCommuniteDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  #network
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Moya'
  
  #model
  pod 'ObjectMapper' #配合https://github.com/Ahmed-Ali/JSONExport 快速建立model
  pod 'SwiftyJSON'
  
  #UI
  pod 'MJRefresh'
  pod 'SnapKit'
  pod 'TYCyclePagerView'
  pod 'TYPagerController'
  pod 'SDCycleScrollView'
  pod 'ESTabBarController-swift' #带点击动画的tabbar
  pod 'LZImageBrowser' #图片浏览器
  pod 'Charts'
  pod 'JXSegmentedView', '~> 0.0.19' #分页控制器
  pod 'JXPagingView/Paging', '~> 1.1.15'#分页控制器
  pod 'PlaceholderTextView'
  pod 'HXPhotoPicker' #图片浏览器
  pod 'GrowingTextView', '0.7.0'
  pod 'YYText'
  pod 'DYFoldLabel'
  
  #Toast
  pod 'Toast-Swift' #弹出信息
  pod 'MBProgressHUD' #弹出信息
  
  #rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'

  #other
  pod 'Reusable'
  pod 'Then'
  pod 'KeychainAccess' #keychain
  pod 'IQKeyboardManagerSwift'
  pod 'Bugly'

end
